services:
  my_app:
    working_dir: /workspace
    build:
      context: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
    networks:
      - devcontainer_network
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports: 
      - "3000:3000"
    environment:
      - HOST_URL=example.dev
    networks:
      - devcontainer_network
networks:
  devcontainer_network:
    driver: bridge